//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryManagementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class invDatabase
    {
        public string itemName { get; set; }
        public int itemQty { get; set; }
        public string itemLocation { get; set; }
        public string itemClass { get; set; }
    }
}
